default_stages: [commit]

default_language_version:
  python: python3.10

ci:
    skip: [autoflake]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=2048']
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer

#  - repo: https://github.com/codespell-project/codespell
#    rev: v2.2.1
#    hooks:
#      - id: codespell

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [
          --profile,
          black,
          --filter-files
        ]
        name: isort (python)

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [ python ]
        require_serial: true
        args: [
            --in-place,
            --expand-star-imports,
            --remove-duplicate-keys,
            --remove-unused-variables,
          ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.5.1
    hooks:
      - id: add-trailing-comma
        args:
          - --py36-plus

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      args: [
        --skip-string-normalization,
        --line-length=120,
        --target-version=py310
      ]
      exclude: ^(venv/|docs/)
      types: ['python']

  - repo: https://github.com/myint/unify
    rev: v0.5
    hooks:
      - id: unify
        args: [
          --in-place,
          --recursive,
        ]
        exclude: ^(venv/|docs/)
        types: [ 'python' ]

 # - repo: https://github.com/PyCQA/flake8
 #   rev: 5.0.4
 #   hooks:
 #     - id: flake8
 #       args: [
 #         --max-line-length=140
 #       ]
 #       exclude: ^(venv/|docs/)
 #       types: [ 'python' ]

  # pyment anime_recommender/ --output numpydoc -w
  # pre-commit run --all-files
  # pre-commit install
